### ISSUE TITLE
你好，大佬，同步QQ/网易云歌单的问题来这里打扰了...

### ISSUE THREAD

**Issue by shuer001** [baozaodetudou/Hackintosh-Maxsun-B760itx-13600k-RX580#3]
MP同步QQ/网易云歌单插件的反馈。
插件已经很好用，有效的解决了歌单问题，非常感谢。

因为各大平台歌曲的标题-歌手命名差异等。  
能不能：
①标题忽略（）里内容， 
②歌手名是多歌手 只要能命中一个，就可以加入歌单。 有两个情况 1是QQ音乐是A/B ，但我存的是A。  2是AQQ音乐是A，但我存的是A/B。
③ 因为都是NAS存的歌，标签都是削刮和自己的习惯保存的，如果歌手G.E.M.邓紫棋  伍佰 & China Blue   我都是改成邓紫棋 伍佰 这样来保存的，这样的有办法匹配吗？   应该比较难，③可以忽略。。。

冒昧打扰了。

**Comment by baozaodetudou** [comment]
抱歉，我刚刚打开了https://github.com/baozaodetudou/MoviePilot-Plugins/issues 。针对问题可以转移过去
